// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMyeI_p4yq0rEMdvYNeOS6pqoyoDEApo',
    appId: '1:287437154173:web:79dd9ab8e8acfb9afc4e14',
    messagingSenderId: '287437154173',
    projectId: 'weather-42303',
    authDomain: 'weather-42303.firebaseapp.com',
    storageBucket: 'weather-42303.firebasestorage.app',
    measurementId: 'G-T8LWLSXN3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1XbSu9CBWMDynupD6TcroI9ZDmU-pFs',
    appId: '1:287437154173:android:2faddfbb2209aa6dfc4e14',
    messagingSenderId: '287437154173',
    projectId: 'weather-42303',
    storageBucket: 'weather-42303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpEjzukjEVmUvBARaRnZCYEPocET6IPo',
    appId: '1:287437154173:ios:62ca83f6ded09d93fc4e14',
    messagingSenderId: '287437154173',
    projectId: 'weather-42303',
    storageBucket: 'weather-42303.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKpEjzukjEVmUvBARaRnZCYEPocET6IPo',
    appId: '1:287437154173:ios:62ca83f6ded09d93fc4e14',
    messagingSenderId: '287437154173',
    projectId: 'weather-42303',
    storageBucket: 'weather-42303.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuMyeI_p4yq0rEMdvYNeOS6pqoyoDEApo',
    appId: '1:287437154173:web:6e8bce1eeb5502e9fc4e14',
    messagingSenderId: '287437154173',
    projectId: 'weather-42303',
    authDomain: 'weather-42303.firebaseapp.com',
    storageBucket: 'weather-42303.firebasestorage.app',
    measurementId: 'G-78XH99RY3J',
  );
}
